### ISSUE TITLE
Import photo from gallery option implement 

### ISSUE THREAD

**Issue by maityamit** [myselfdeepdas/Face-App#7]
Import photo from gallery option implement 

As of now only camera photo work. 
But I will implement one function that will import photo from gallery.

![Screenshot 2022-10-09 170451](https://user-images.githubusercontent.com/74618071/194757637-41a9c069-5fdd-4d59-9618-aa1d4d420b8b.png)

**Comment by myselfdeepdas** [comment]
yes!! go ahed @maityamit
